// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2SEyqlVVW2GciAJJ7se4RQbgWzCz12Q',
    appId: '1:147406472326:web:0f9ccf5ce2eea56279fd07',
    messagingSenderId: '147406472326',
    projectId: 'mk-music-2195b',
    authDomain: 'mk-music-2195b.firebaseapp.com',
    storageBucket: 'mk-music-2195b.appspot.com',
    measurementId: 'G-NPQMP25GM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu_4thARTt0YY575Xm0rW1rgPakO2B1WU',
    appId: '1:147406472326:android:b0062b8564d106b879fd07',
    messagingSenderId: '147406472326',
    projectId: 'mk-music-2195b',
    storageBucket: 'mk-music-2195b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh66uQ13WUxKC-lAy5jmuh7AYdGK-WLmE',
    appId: '1:147406472326:ios:4ad8b51b44b284d079fd07',
    messagingSenderId: '147406472326',
    projectId: 'mk-music-2195b',
    storageBucket: 'mk-music-2195b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh66uQ13WUxKC-lAy5jmuh7AYdGK-WLmE',
    appId: '1:147406472326:ios:398156e5e939a79d79fd07',
    messagingSenderId: '147406472326',
    projectId: 'mk-music-2195b',
    storageBucket: 'mk-music-2195b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
